language: ruby

rvm:
- 2.4.3
- 2.5.0

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - WAIT_FOR_JEKYLL=10

sudo: false # route your build to the container-based infrastructure for a faster build
